<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>11</LangVersion>
        <RootNamespace>Oxide.Plugins</RootNamespace>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>nullable</WarningsAsErrors>
        <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
        <NoStandardLibraries>true</NoStandardLibraries>
        <NoStdLib>true</NoStdLib>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
        <NoCompilerStandardLib>true</NoCompilerStandardLib>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="BroadcastPreferences.cs" />
        <Compile Remove="server/oxide/plugins/*.cs" />
    </ItemGroup>

    <ItemGroup>
        <Reference
            Include="server/RustDedicated_Data/Managed\*.dll"
            Exclude="
                server\RustDedicated_Data\Managed\Newtonsoft.Json.dll;
                server\RustDedicated_Data\Managed\System.Net.Http.dll;
                server\RustDedicated_Data\Managed\Microsoft.Win32.Registry.dll;
                server\RustDedicated_Data\Managed\System.Threading.Tasks.Extensions.dll;
                server\RustDedicated_Data\Managed\System.Configuration.Install.dll;
                server\RustDedicated_Data\Managed\System.IO.Compression.dll;
                server\RustDedicated_Data\Managed\System.Runtime.dll;
                server\RustDedicated_Data\Managed\System.IO.FileSystem.AccessControl.dll;
                server\RustDedicated_Data\Managed\System.Security.Principal.Windows.dll;
                server\RustDedicated_Data\Managed\System.Security.AccessControl.dll;
                server\RustDedicated_Data\Managed\Microsoft.Bcl.AsyncInterfaces.dll;
                server\RustDedicated_Data\Managed\System.Text.Encodings.Web.dll;
                server\RustDedicated_Data\Managed\System.Security.Cryptography.ProtectedData.dll;
                server\RustDedicated_Data\Managed\System.Numerics.Vectors.dll;
            "
            Private="false"
        />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="dotnet tool run plugin.merge -- -m -c -p merge.json" />
        <Exec Command="dotnet tool run csharpier -- format ." />
    </Target>
</Project>
